### ISSUE TITLE
Foxy Branch Build Broken

### ISSUE THREAD

**Issue by jtcass01** [ros-planning/moveit2#1197]
### Description

Foxy Branch is missing proper moveit2 repos file. Had to replace with my own file to get it to properly build.

### Your environment
* ROS Distro: Foxy
* OS Version: Ubuntu 20.04
* Source or Binary build: Source

### Steps to reproduce
I ran the following commands on my jetson nano after updating to Ubuntu 20.04:

```bash
sudo apt upgrade

# installing ros2
sudo apt update && sudo apt install locales
sudo locale-gen en_US en_US.UTF-8
sudo update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
export LANG=en_US.UTF-8
sudo apt update && sudo apt install curl gnupg2 lsb-release
sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key  -o /usr/share/keyrings/ros-archive-keyring.gpg
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(source /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
sudo apt update
sudo apt install ros-foxy-desktop
source /opt/ros/foxy/setup.bash
ros2 run demo_nodes_cpp talker

# Setting up Ros2 robot driver
sudo apt install python3-colcon-common-extensions python3-vcstool python-rosdep
export COLCON_WS=~/workspace/ros_ur_driver
mkdir -p $COLCON_WS/src
cd $COLCON_WS
git clone https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver.git src/Universal_Robots_ROS2_Driver
cd src/Universal_Robots_ROS2_Driver
git checkout foxy
git pull origin foxy
cd $COLCON_WS
vcs import src --skip-existing --input src/Universal_Robots_ROS2_Driver/Universal_Robots_ROS2_Driver.repos
rosdep update
rosdep install --ignore-src --from-paths src -y -r
colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release
source install/setup.bash

# Setting up Ros2 robot driver with moveit2
cd $COLCON_WS
vcs import src --skip-existing --input src/Universal_Robots_ROS2_Driver/MoveIt_Support.repos
# Having to fix moveit2.repos
cd $COLCON_WS/src/Universal_Robots_ROS2_Driver/moveit2
nano moveit2.repos
```

Writing the following inside of moveit2.repos:
```yaml
repositories:
  geometric_shapes:
    type: git
    url: https://github.com/ros-planning/geometric_shapes
    version: foxy
  moveit_resources:
    type: git
    url: https://github.com/ros-planning/moveit_resources
    version: ros2
  srdfdom:
    type: git
    url: https://github.com/ros-planning/srdfdom.git
    version: foxy
```

#### Finishing build with moveit2
```bash
cd $COLCON_WS
vcs import src --skip-existing --input src/Universal_Robots_ROS2_Driver/moveit2.repos
rosdep update
rosdep install --ignore-src --from-paths src -y -r
colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release
```

### Expected behavior
The package should have built.

### Actual behavior
It produced errors when sourcing from srdfdom. When using apt-get install srdfdom, it was unable to produce a path claiming all joints were in collision.  Fixed by rebuilding with new moveit2.repos file.
