### ISSUE TITLE
Moveit Servo producing strage jiggling commands

### ISSUE THREAD

**Issue by andrey-pr** [ros-planning/moveit2#2108]
### Description

Hello. I tested Moveit Servo on my custom robot, and it jiggles.
Here is a plot of data from one of axises:
![изображение](https://user-images.githubusercontent.com/22261051/231783098-fbe0eac9-9b60-4128-995e-ae16cffcc802.png)
As we can see, value returns back every second time. Its produces vibration on real robot.

Thank you for your help

```
###############################################
# Modify all parameters related to servoing here
###############################################
use_gazebo: false # Whether the robot is started in a Gazebo simulation environment

## Properties of incoming commands
command_in_type: "unitless" # "unitless"> in the range [-1:1], as if from joystick. "speed_units"> cmds are in m/s and rad/s
scale:
  # Scale parameters are only used if command_in_type=="unitless"
  linear:  0.4  # Max linear velocity. Meters per publish_period. Unit is [m/s]. Only used for Cartesian commands.
  rotational:  0.8 # Max angular velocity. Rads per publish_period. Unit is [rad/s]. Only used for Cartesian commands.
  # Max joint angular/linear velocity. Rads or Meters per publish period. Only used for joint commands on joint_command_in_topic.
  joint: 0.5

## Properties of outgoing commands
publish_period: 0.05  # 1/Nominal publish rate [seconds]
low_latency_mode: false  # Set this to true to publish as soon as an incoming Twist command is received (publish_period is ignored)

# What type of topic does your robot driver expect?
# Currently supported are std_msgs/Float64MultiArray or trajectory_msgs/JointTrajectory
command_out_type: trajectory_msgs/JointTrajectory

# What to publish? Can save some bandwidth as most robots only require positions or velocities
publish_joint_positions: true
publish_joint_velocities: false
publish_joint_accelerations: false

## Plugins for smoothing outgoing commands
smoothing_filter_plugin_name: "online_signal_smoothing::ButterworthFilterPlugin"

## MoveIt properties
move_group_name:  right_arm_group  # Often 'manipulator' or 'arm'
planning_frame: leg  # The MoveIt planning frame. Often 'base_link' or 'world'

## Other frames
ee_frame_name: right_gripper_base  # The name of the end effector link, used to return the EE pose
robot_link_command_frame:  leg  # commands must be given in the frame of a robot link. Usually either the base or end effector

## Stopping behaviour
incoming_command_timeout:  0.1  # Stop servoing if X seconds elapse without a new command
# If 0, republish commands forever even if the robot is stationary. Otherwise, specify num. to publish.
# Important because ROS may drop some messages and we need the robot to halt reliably.
num_outgoing_halt_msgs_to_publish: 4

## Configure handling of singularities and joint limits
lower_singularity_threshold:  1000.0  # Start decelerating when the condition number hits this (close to singularity)
hard_stop_singularity_threshold: 1500.0 # Stop when the condition number hits this
joint_limit_margin: 0.1 # added as a buffer to joint limits [radians]. If moving quickly, make this larger.

## Topic names
cartesian_command_in_topic: /robol/servo/right_arm/delta_twist_cmds  # Topic for incoming Cartesian twist commands
joint_command_in_topic: /robol/servo/right_arm/delta_joint_cmds # Topic for incoming joint angle commands
joint_topic: /joint_states
status_topic: /robol/servo/right_arm/status # Publish status to this topic
command_out_topic: /right_arm_controller/joint_trajectory # Publish outgoing commands here

## Collision checking for the entire robot body
check_collisions: true # Check collisions?
collision_check_rate: 100.0 # [Hz] Collision-checking can easily bog down a CPU if done too often.
# Two collision check algorithms are available:
# "threshold_distance" begins slowing down when nearer than a specified distance. Good if you want to tune collision thresholds manually.
# "stop_distance" stops if a collision is nearer than the worst-case stopping distance and the distance is decreasing. Requires joint acceleration limits
collision_check_type: threshold_distance
# Parameters for "threshold_distance"-type collision checking
self_collision_proximity_threshold: 0.03 # Start decelerating when a self-collision is this far [m]
scene_collision_proximity_threshold: 0.03 # Start decelerating when a scene collision is this far [m]
# Parameters for "stop_distance"-type collision checking
collision_distance_safety_factor: 1000.0 # Must be >= 1. A large safety factor is recommended to account for latency
min_allowable_collision_distance: 0.01 # Stop if a collision is closer than this [m]
```

### My environment
* ROS Distro: Humble
* OS Version: e.g. Ubuntu 22.04
* Binary build
* 2.5.4-1jammy.20230327.202336
* Cyclone DDS.

**Comment by AndyZe** [comment]
I can't say for sure but you could try increasing the low-pass filter coefficient. This should result in smoother motion. This is achieved with a parameter, as you can see in this PR:

https://github.com/ros-planning/moveit2/pull/2091

The parameter name is `butterworth_filter_coeff`. It defaults to 1.5 and it should be >1 always.

**Comment by AndyZe** [comment]
I would put it in the launch file, around here for example:

https://github.com/ros-planning/moveit2/blob/884813de0b01556977e76373ca07ad5870d74500/moveit_ros/moveit_servo/launch/servo_example.launch.py#L142

I can make a PR to demonstrate this later today  :+1:

**Comment by andrey-pr** [comment]
> 

Is this parameter supported in humble or only in rolling?

**Comment by andrey-pr** [comment]
> Rolling only. Sorry.

I think maybe I can make a PR with this parameter to humble branch - its just a 3 changes lines in file
![изображение](https://user-images.githubusercontent.com/22261051/231789499-ad111017-6874-47cf-a063-25b32ede9685.png)

**Comment by AndyZe** [comment]
+1 to that idea.

You could also try adjusting the rate. Maybe there's some type of resonance/feedback that's particular to your hardware.

**Comment by andrey-pr** [comment]
> I can't say for sure but you could try increasing the low-pass filter coefficient. This should result in smoother motion. This is achieved with a parameter, as you can see in this PR:
> 
> #2091
> 
> The parameter name is `butterworth_filter_coeff`. It defaults to 1.5 and it should be >1 always.

I tested this param. High values, such as 50 or 100 reduces jiggling, but bot completely, and it reduces speed also in several times. What can I do also to solve problem?

**Comment by AndyZe** [comment]
What commit are you on, exactly?

It's possible that this commit started producing weird behavior so please test both prior to and after this commit:  

https://github.com/ros-planning/moveit2/pull/2080

**Comment by andrey-pr** [comment]
>  +1 to that idea.
>
>   You could also try adjusting the rate. Maybe there's some type of resonance/feedback that's particular to your hardware.


Hello. I'm trying to move changes from rolling to humble, but currently I'm not understand how to set coefficient in servo config file. String `butterworth_filter_coeff: 100` doesn't works, maybe this parameter way to set

**Comment by AndyZe** [comment]
On humble, that parameter is hard-coded here:  https://github.com/ros-planning/moveit2/blob/f8b764b09d453f4b212b7fd373009f951aac6646/moveit_core/online_signal_smoothing/src/butterworth_filter.cpp#L104

**Comment by andrey-pr** [comment]
> On humble, that parameter is hard-coded here:
> 
> https://github.com/ros-planning/moveit2/blob/f8b764b09d453f4b212b7fd373009f951aac6646/moveit_core/online_signal_smoothing/src/butterworth_filter.cpp#L104

I moved changed from https://github.com/ros-planning/moveit2/pull/2091 to humble branch copy on my computed. It must take argument from file, but I didn't understand how to name this argument

**Comment by AndyZe** [comment]
I see. Example here:  https://github.com/ros-planning/moveit2/blob/acbf3770763e58e4f86ce0dea251a50cd4987fe6/moveit_ros/moveit_servo/launch/servo_example.launch.py#L46

**Comment by schornakj** [comment]
Just wanted to +1 this, since I started seeing this on my UR5e after upgrading from MoveIt 2.6 to MoveIt 2.7. I didn't change the robot's servo config when upgrading, so I think this is the result of something changing in the implementation of Servo between those versions.

**Comment by andrey-pr** [comment]
I made a PR https://github.com/ros-planning/moveit2/pull/2129 with changes from https://github.com/ros-planning/moveit2/pull/2091 as I promised on last week. @AndyZe can you check & merge it, please?

**Comment by andrey-pr** [comment]
> What commit are you on, exactly?
> 
> It's possible that this commit started producing weird behavior so please test both prior to and after this commit:
> 
> #2080

This problem reproduces on moveit 2.5 and on latest commits from humble branch

**Comment by andrey-pr** [comment]
> Just wanted to +1 this, since I started seeing this on my UR5e after upgrading from MoveIt 2.6 to MoveIt 2.7. I didn't change the robot's servo config when upgrading, so I think this is the result of something changing in the implementation of Servo between those versions.

I spotted this problem even on 2.5

**Comment by ibrahiminfinite** [comment]
> Just wanted to +1 this, since I started seeing this on my UR5e after upgrading from MoveIt 2.6 to MoveIt 2.7. I didn't change the robot's servo config when upgrading, so I think this is the result of something changing in the implementation of Servo between those versions.

@AndyZe 
#2080  is only in 2.7.1 
Could this issue be related to the drift issue ?

**Comment by AndyZe** [comment]
I really don't know. @schornakj says the issue is recent, @andrey-pr says it's been happening since last year (MoveIt 2.5.4 was November 2022). 

@schornakj if you can try reverting recent PR's to bisect the issue, that would be really helpful. #2080 is the most likely suspect IMO

**Comment by andrey-pr** [comment]
> I really don't know. @schornakj says the issue is recent, @andrey-pr says it's been happening since last year (MoveIt 2.5.4 was November 2022). 
> 
> @schornakj if you can try reverting recent PR's to bisect the issue, that would be really helpful. #2080 is the most likely suspect IMO

I don't know exactly if it happens since 2.5.4 or it started earlier. I just know that it reproduces on package from ros apt repo for ubuntu 22.04 with version 2.5.4, but maybe it started earlier

**Comment by andrey-pr** [comment]
I'll try to check if problem exists on 2.4

**Comment by andrey-pr** [comment]
> I'll try to check if problem exists on 2.4

I tried but didn't have success in launching, because of problems with dependencies

**Comment by ibrahiminfinite** [comment]
@AndyZe  #2136 Looks like the same issue .

**Comment by andrey-pr** [comment]
![изображение](https://user-images.githubusercontent.com/22261051/234368880-b758bff5-0f77-4c95-a79c-950ea58c273e.png)
@AndyZe I added parameter `open_loop_control: true` to controller config and it became better, but problem fixed not completely. After every command in `/right_arm_controller/joint_trajectory` topic it starts to send command from old place. As I guess, if moveit servo would send commands slightly more often, than command can be executed (by `time_from_start`) maybe it can help, but i don't know how to tune it

**Comment by ibrahiminfinite** [comment]
@andrey-pr 
Have you tried changing the `publish_period` ?
https://github.com/ros-planning/moveit2/blob/acbf3770763e58e4f86ce0dea251a50cd4987fe6/moveit_ros/moveit_servo/config/panda_simulated_config.yaml#L19

**Comment by andrey-pr** [comment]
> @andrey-pr Have you tried changing the `publish_period` ?
> 
> https://github.com/ros-planning/moveit2/blob/acbf3770763e58e4f86ce0dea251a50cd4987fe6/moveit_ros/moveit_servo/config/panda_simulated_config.yaml#L19

Yes, currently I use 0.15 value. It jiggles every new command, now with 0.15 rate

**Comment by ibrahiminfinite** [comment]
@andrey-pr 
You should take a look at #2136 , maybe it is something to do with your controller settings?
Not sure about it , but you might find something relevant in the discussion there

**Comment by andrey-pr** [comment]
> 

I didn't find solution in #2136. I use JointTrajectoryController as recommended there. There are no different controllers that support hardware with position only interface

**Comment by andrey-pr** [comment]
I modified my hardware emulator, how it doesn't emulate movement with several constant speeds, but returns as state value that it got from commands. Now signal plot doesn't returns back, but still have pairs of equal values every 0.15s (servo command rate). As I think, after every command controller starts with command of already existing value. I tried to double time of execution servo command with old rate, but it didn't change anything. So, maybe controller starts every period with sending old position. What can I do with it?

**Comment by ibrahiminfinite** [comment]
> still have pairs of equal values every 0.15s (servo command rate). As I think, after every command controller starts with command of already existing value.

Can you try plotting the commands the controller received from servo and the commands that the controller is actually sending to the robot ?
Maybe it is the controller that is causing the jerking like you mentioned and not the servo.

Also which version of Moveit2 are you on now ?

**Comment by andrey-pr** [comment]
> > still have pairs of equal values every 0.15s (servo command rate). As I think, after every command controller starts with command of already existing value.
> 
> Can you try plotting the commands the controller received from servo and the commands that the controller is actually sending to the robot ? Maybe it is the controller that is causing the jerking like you mentioned and not the servo.
> 
> Also which version of Moveit2 are you on now ?

Yes, controller causing jerking by sending command on hardware that identically to previous state after every receiving of command in topic, but we have to found some solution to make moveit servo usable. I reproduced it on 2.5.4 and on 2.7.3, as I guess, problem exists on all of versions between and maybe on some earlier versions

**Comment by gavanderhoorn** [comment]
> didn't find solution in #2136. I use JointTrajectoryController as recommended there.

Doesn't that discussion say to *not* use `JointTrajectoryController`?

Servo with a `JointTrajectoryController` doesn't make too much sense to me, unless Servo is running at a *much* lower frequency than your driver/controller, at which point interpolation between sparse Servo output *might* make sense.

But I guess @AndyZe would know best here.

**Comment by andrey-pr** [comment]
> > didn't find solution in #2136. I use JointTrajectoryController as recommended there.
> 
> Doesn't that discussion suggest *not* to use `JointTrajectoryController`?
> 
> Servo with a `JointTrajectoryController` doesn't make too much sense to me, unless Servo is running at a *much* lower frequency than your driver/controller, at which point interpolation between sparse Servo output *might* make sense.
> 
> But I guess @AndyZe would know best here.
> 

What different controller can I use? I think I have no alternative

**Comment by andrey-pr** [comment]
> > didn't find solution in #2136. I use JointTrajectoryController as recommended there.
> 
> Doesn't that discussion suggest *not* to use `JointTrajectoryController`?
> 
> Servo with a `JointTrajectoryController` doesn't make too much sense to me, unless Servo is running at a *much* lower frequency than your driver/controller, at which point interpolation between sparse Servo output *might* make sense.
> 
> But I guess @AndyZe would know best here.
> 

What different controller can I use? I think I have no alternative

**Comment by gavanderhoorn** [comment]
`JointGroupVelocityController` or `JointGroupPositionController`.

**Comment by gavanderhoorn** [comment]
> Is `JointGroupPositionController` compatible with MoveGroup api?

not directly.

But the idea is to *switch* controllers when you need them.

So `JointGroupPositionController` for Servo/direct control, `JointTrajectoryController` for executing complete `FollowJointTrajectory` goals.

**Comment by AndyZe** [comment]
I wonder if your `/joint_state` publication rate needs to be increased. I believe that is adjusted right here:

https://github.com/ros-controls/ros2_control_demos/blob/1612c4cf263b08f362f9a5573978ed766103d6dc/example_1/bringup/config/rrbot_controllers.yaml#L3

**Comment by andrey-pr** [comment]
> I wonder if your /joint_state publication rate needs to be increased. 

Usually I use 50hz, default value is 100hz. I tried to set 100hz, but it didn't help

**Comment by andrey-pr** [comment]
> > Is `JointGroupPositionController` compatible with MoveGroup api?
> 
> not directly.
> 
> But the idea is to _switch_ controllers when you need them.
> 
> So `JointGroupPositionController` for Servo/direct control, `JointTrajectoryController` for executing complete `FollowJointTrajectory` goals.

Yes, but how to switch controllers without reloading? Is there good way to do it?

**Comment by andrey-pr** [comment]
> > Is `JointGroupPositionController` compatible with MoveGroup api?
> 
> not directly.
> 
> But the idea is to _switch_ controllers when you need them.
> 
> So `JointGroupPositionController` for Servo/direct control, `JointTrajectoryController` for executing complete `FollowJointTrajectory` goals.

Thank you very much. It fixed the problem. Now the only question I have is how to switch between controllers without stop & launch with different launch file?

**Comment by andrey-pr** [comment]
> @andrey-pr 
> Did the fix involve just the change of controller to `JointGroupPositionController` or did you change anything else in your original configuration as well ?

I changed servo configs to work with this controller. I changed out topic address, message type and adjusted publish rate - it should be equal to controller manager update rate to get maximal effeciency

**Comment by andrey-pr** [comment]
> @andrey-pr 
> Did the fix involve just the change of controller to `JointGroupPositionController` or did you change anything else in your original configuration as well ?

I changed servo configs to work with this controller. I changed out topic address, message type and adjusted publish rate - it should be equal to controller manager update rate to get maximal effeciency

**Comment by andrey-pr** [comment]
![изображение](https://user-images.githubusercontent.com/22261051/235185009-71459cbe-5cdb-4ff8-bb9c-3d5a104c726b.png)
This plot made with publish period 0.15
![изображение](https://user-images.githubusercontent.com/22261051/235185174-452d1ce0-1e91-4961-b84b-010812049ec8.png)
This plot made with publish period 0.034
![изображение](https://user-images.githubusercontent.com/22261051/235184911-2aaa593c-67e4-4066-875e-cd69bda373c3.png)
This plot made with publish period 0.02
Frequency from controller manager is 50HZ

**Comment by ibrahiminfinite** [comment]
Awesome! 
Thanks for the plots

**Comment by AndyZe** [comment]
Glad you got this sorted out! This points suspicion toward the `joint_trajectory_controller`, I would say.

`
Now the only question I have is how to switch between controllers without stop & launch with different launch file?`

That's easy. You can do it from the command line or make a service call:

https://control.ros.org/master/doc/ros2_control/ros2controlcli/doc/userdoc.html

**Comment by andrey-pr** [comment]
> Glad you got this sorted out! This points suspicion toward the `joint_trajectory_controller`, I would say.
> 
> `
> Now the only question I have is how to switch between controllers without stop & launch with different launch file?`
> 
> That's easy. You can do it from the command line or make a service call:
> 
> https://control.ros.org/master/doc/ros2_control/ros2controlcli/doc/userdoc.html

Thank you for advice

**Comment by andrey-pr** [comment]
Finally, I fixed my program.
Here is the parts of code that fixing problem:
`ros_controllers.yaml`
```yaml
controller_manager:
  ros__parameters:
    update_rate: 50  # Hz
    right_arm_group_controller:
      type: position_controllers/JointGroupPositionController

    right_arm_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

...

right_arm_group_controller:
  ros__parameters:
    joints:
      - torso_right_shoulder_top_joint
      - right_shoulder_top_right_shoulder_bottom_joint
      - right_shoulder_bottom_right_forearm_joint
      - right_forearm_right_forearm_bottom_joint
      - right_forearm_bottom_right_wrist_joint
      - right_wrist_right_gripper_base_joint


right_arm_trajectory_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
    joints:
      - torso_right_shoulder_top_joint
      - right_shoulder_top_right_shoulder_bottom_joint
      - right_shoulder_bottom_right_forearm_joint
      - right_forearm_right_forearm_bottom_joint
      - right_forearm_bottom_right_wrist_joint
      - right_wrist_right_gripper_base_joint
...
```

`servo_config.yaml`

```yaml
...
publish_period: 0.02 #1/controller_manager_update_rate
...
command_out_type: std_msgs/Float64MultiArray
...
command_out_topic: /right_arm_group_controller/commands
```

`demo.launch.py`

```python
...
load_controllers = []
for controller in ["right_arm_trajectory_controller", "joint_state_broadcaster"]:
    load_controllers += [
        ExecuteProcess(
            cmd=["ros2 run controller_manager spawner {}".format(controller)],
            shell=True,
            output="screen",
        )
    ]
        
 load_controllers += [
        ExecuteProcess(
            cmd=["ros2 run controller_manager spawner --inactive right_arm_group_controller"],
            shell=True,
            output="screen",
        )
    ]
...
```

`src.cpp` - file that performs switching from MoveGroup to Servo

```cpp
...
rclcpp::Client<controller_manager_msgs::srv::SwitchController>::SharedPtr switch_controller_service =  m_clientNode->create_client<controller_manager_msgs::srv::SwitchController>(
      "/controller_manager/switch_controller");
while (!switch_controller_service->wait_for_service(1s))
  {
    if (!rclcpp::ok())
    {
      RCLCPP_ERROR(rclcpp::get_logger("rclcpp"), "Interrupted while waiting for the service. Exiting.");
    }
    RCLCPP_INFO(rclcpp::get_logger("rclcpp"), "service not available, waiting again...");
  }
...
auto request = std::make_shared<controller_manager_msgs::srv::SwitchController::Request>();
request->activate_controllers = { "right_arm_group_controller" };
request->deactivate_controllers = { "right_arm_trajectory_controller" };
request->strictness = controller_manager_msgs::srv::SwitchController::Request::BEST_EFFORT;
request->timeout = rclcpp::Duration(0, 0);
auto result = switch_controller_service->async_send_request(request);
rclcpp::spin_until_future_complete(m_clientNode, result);
```

`src2.cpp` - file that performs switching from Servo to MoveGroup

```cpp
...
rclcpp::Client<controller_manager_msgs::srv::SwitchController>::SharedPtr switch_controller_service =  m_clientNode->create_client<controller_manager_msgs::srv::SwitchController>(
      "/controller_manager/switch_controller");
while (!switch_controller_service->wait_for_service(1s))
  {
    if (!rclcpp::ok())
    {
      RCLCPP_ERROR(rclcpp::get_logger("rclcpp"), "Interrupted while waiting for the service. Exiting.");
    }
    RCLCPP_INFO(rclcpp::get_logger("rclcpp"), "service not available, waiting again...");
  }
...
auto request = std::make_shared<controller_manager_msgs::srv::SwitchController::Request>();
request->activate_controllers = { "right_arm_trajectory_controller" };
request->deactivate_controllers = { "right_arm_group_controller" };
request->strictness = controller_manager_msgs::srv::SwitchController::Request::BEST_EFFORT;
request->timeout = rclcpp::Duration(0, 0);
auto result = switch_controller_service->async_send_request(request);
rclcpp::spin_until_future_complete(m_clientNode, result);
```

Lots of things used here are undocumented or badly documented.
I hope it will help somebody
