### ISSUE TITLE
moveit2 ros2 humble bug in custom robot,

### ISSUE THREAD

**Issue by faheem-khaskheli** [ros-planning/moveit2#2258]
# Setting
i am using a robot tiago ++ from webots, i exported robot as urdf, after which i have created cusotm moveit config, using setup assistant, when i run demo i give left arm a goal to reach which is valid goal, it stop working after reaching that goal.

i have made sure max_velocity and max_acceleration are float values.

# Error
[ros2_control_node-5] [INFO] [1688365040.209568727] [left_arm_controller]: Received new action goal
[ros2_control_node-5] [INFO] [1688365040.209691727] [left_arm_controller]: Accepted new action goal
[move_group-3] [INFO] [1688365040.210590729] [moveit.simple_controller_manager.follow_joint_trajectory_controller_handle]: left_arm_controller started execution
[move_group-3] [INFO] [1688365040.210633729] [moveit.simple_controller_manager.follow_joint_trajectory_controller_handle]: Goal request accepted!
[move_group-3] [WARN] [1688365040.236972182] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: The complete state of the robot is not yet known.  Missing CASTER_WHEEL_BACK_LEFT_JOINT, SMALL_WHEEL_JOINT, CASTER_WHEEL_BACK_RIGHT_JOINT, SMALL_WHEEL_JOINT_0, CASTER_WHEEL_FRONT_LEFT_JOINT, SMALL_WHEEL_JOINT_1, CASTER_WHEEL_FRONT_RIGHT_JOINT, SMALL_WHEEL_JOINT_2, torso_lift_joint, head_1_joint, head_2_joint, wheel_left_joint, wheel_right_joint
[move_group-3] [WARN] [1688365041.246441217] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: The complete state of the robot is not yet known.  Missing CASTER_WHEEL_BACK_LEFT_JOINT, SMALL_WHEEL_JOINT, CASTER_WHEEL_BACK_RIGHT_JOINT, SMALL_WHEEL_JOINT_0, CASTER_WHEEL_FRONT_LEFT_JOINT, SMALL_WHEEL_JOINT_1, CASTER_WHEEL_FRONT_RIGHT_JOINT, SMALL_WHEEL_JOINT_2, torso_lift_joint, head_1_joint, head_2_joint, wheel_left_joint, wheel_right_joint
[move_group-3] [WARN] [1688365042.246901862] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: The complete state of the robot is not yet known.  Missing CASTER_WHEEL_BACK_LEFT_JOINT, SMALL_WHEEL_JOINT, CASTER_WHEEL_BACK_RIGHT_JOINT, SMALL_WHEEL_JOINT_0, CASTER_WHEEL_FRONT_LEFT_JOINT, SMALL_WHEEL_JOINT_1, CASTER_WHEEL_FRONT_RIGHT_JOINT, SMALL_WHEEL_JOINT_2, torso_lift_joint, head_1_joint, head_2_joint, wheel_left_joint, wheel_right_joint
[move_group-3] [WARN] [1688365043.266543297] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: The complete state of the robot is not yet known.  Missing CASTER_WHEEL_BACK_LEFT_JOINT, SMALL_WHEEL_JOINT, CASTER_WHEEL_BACK_RIGHT_JOINT, SMALL_WHEEL_JOINT_0, CASTER_WHEEL_FRONT_LEFT_JOINT, SMALL_WHEEL_JOINT_1, CASTER_WHEEL_FRONT_RIGHT_JOINT, SMALL_WHEEL_JOINT_2, torso_lift_joint, head_1_joint, head_2_joint, wheel_left_joint, wheel_right_joint
[move_group-3] [WARN] [1688365044.276735112] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: The complete state of the robot is not yet known.  Missing CASTER_WHEEL_BACK_LEFT_JOINT, SMALL_WHEEL_JOINT, CASTER_WHEEL_BACK_RIGHT_JOINT, SMALL_WHEEL_JOINT_0, CASTER_WHEEL_FRONT_LEFT_JOINT, SMALL_WHEEL_JOINT_1, CASTER_WHEEL_FRONT_RIGHT_JOINT, SMALL_WHEEL_JOINT_2, torso_lift_joint, head_1_joint, head_2_joint, wheel_left_joint, wheel_right_joint
[move_group-3] [WARN] [1688365045.277051505] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: The complete state of the robot is not yet known.  Missing CASTER_WHEEL_BACK_LEFT_JOINT, SMALL_WHEEL_JOINT, CASTER_WHEEL_BACK_RIGHT_JOINT, SMALL_WHEEL_JOINT_0, CASTER_WHEEL_FRONT_LEFT_JOINT, SMALL_WHEEL_JOINT_1, CASTER_WHEEL_FRONT_RIGHT_JOINT, SMALL_WHEEL_JOINT_2, torso_lift_joint, head_1_joint, head_2_joint, wheel_left_joint, wheel_right_joint
[move_group-3] [WARN] [1688365046.287102920] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: The complete state of the robot is not yet known.  Missing CASTER_WHEEL_BACK_LEFT_JOINT, SMALL_WHEEL_JOINT, CASTER_WHEEL_BACK_RIGHT_JOINT, SMALL_WHEEL_JOINT_0, CASTER_WHEEL_FRONT_LEFT_JOINT, SMALL_WHEEL_JOINT_1, CASTER_WHEEL_FRONT_RIGHT_JOINT, SMALL_WHEEL_JOINT_2, torso_lift_joint, head_1_joint, head_2_joint, wheel_left_joint, wheel_right_joint
[move_group-3] [WARN] [1688365047.323637696] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: The complete state of the robot is not yet known.  Missing CASTER_WHEEL_BACK_LEFT_JOINT, SMALL_WHEEL_JOINT, CASTER_WHEEL_BACK_RIGHT_JOINT, SMALL_WHEEL_JOINT_0, CASTER_WHEEL_FRONT_LEFT_JOINT, SMALL_WHEEL_JOINT_1, CASTER_WHEEL_FRONT_RIGHT_JOINT, SMALL_WHEEL_JOINT_2, torso_lift_joint, head_1_joint, head_2_joint, wheel_left_joint, wheel_right_joint
[move_group-3] [WARN] [1688365048.356792165] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: The complete state of the robot is not yet known.  Missing CASTER_WHEEL_BACK_LEFT_JOINT, SMALL_WHEEL_JOINT, CASTER_WHEEL_BACK_RIGHT_JOINT, SMALL_WHEEL_JOINT_0, CASTER_WHEEL_FRONT_LEFT_JOINT, SMALL_WHEEL_JOINT_1, CASTER_WHEEL_FRONT_RIGHT_JOINT, SMALL_WHEEL_JOINT_2, torso_lift_joint, head_1_joint, head_2_joint, wheel_left_joint, wheel_right_joint
[move_group-3] [WARN] [1688365049.386524625] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: The complete state of the robot is not yet known.  Missing CASTER_WHEEL_BACK_LEFT_JOINT, SMALL_WHEEL_JOINT, CASTER_WHEEL_BACK_RIGHT_JOINT, SMALL_WHEEL_JOINT_0, CASTER_WHEEL_FRONT_LEFT_JOINT, SMALL_WHEEL_JOINT_1, CASTER_WHEEL_FRONT_RIGHT_JOINT, SMALL_WHEEL_JOINT_2, torso_lift_joint, head_1_joint, head_2_joint, wheel_left_joint, wheel_right_joint
[move_group-3] [WARN] [1688365050.416796687] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: The complete state of the robot is not yet known.  Missing CASTER_WHEEL_BACK_LEFT_JOINT, SMALL_WHEEL_JOINT, CASTER_WHEEL_BACK_RIGHT_JOINT, SMALL_WHEEL_JOINT_0, CASTER_WHEEL_FRONT_LEFT_JOINT, SMALL_WHEEL_JOINT_1, CASTER_WHEEL_FRONT_RIGHT_JOINT, SMALL_WHEEL_JOINT_2, torso_lift_joint, head_1_joint, head_2_joint, wheel_left_joint, wheel_right_joint
[move_group-3] [WARN] [1688365051.456841471] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: The complete state of the robot is not yet known.  Missing CASTER_WHEEL_BACK_LEFT_JOINT, SMALL_WHEEL_JOINT, CASTER_WHEEL_BACK_RIGHT_JOINT, SMALL_WHEEL_JOINT_0, CASTER_WHEEL_FRONT_LEFT_JOINT, SMALL_WHEEL_JOINT_1, CASTER_WHEEL_FRONT_RIGHT_JOINT, SMALL_WHEEL_JOINT_2, torso_lift_joint, head_1_joint, head_2_joint, wheel_left_joint, wheel_right_joint
[move_group-3] [WARN] [1688365052.466747985] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: The complete state of the robot is not yet known.  Missing CASTER_WHEEL_BACK_LEFT_JOINT, SMALL_WHEEL_JOINT, CASTER_WHEEL_BACK_RIGHT_JOINT, SMALL_WHEEL_JOINT_0, CASTER_WHEEL_FRONT_LEFT_JOINT, SMALL_WHEEL_JOINT_1, CASTER_WHEEL_FRONT_RIGHT_JOINT, SMALL_WHEEL_JOINT_2, torso_lift_joint, head_1_joint, head_2_joint, wheel_left_joint, wheel_right_joint
[ros2_control_node-5] [INFO] [1688365052.656169720] [left_arm_controller]: Goal reached, success!
[move_group-3] [INFO] [1688365052.661137031] [moveit.simple_controller_manager.follow_joint_trajectory_controller_handle]: Controller 'left_arm_controller' successfully finished
[move_group-3] [INFO] [1688365052.686752890] [moveit_ros.trajectory_execution_manager]: Completed trajectory execution with status SUCCEEDED ...
[move_group-3] free(): invalid pointer
[move_group-3] Stack trace (most recent call last) in thread 3619:
[move_group-3] #15   Object "", at 0xffffffffffffffff, in 
[move_group-3] #14   Object "/usr/lib/x86_64-linux-gnu/libc.so.6", at 0x7f31c6bb09ff, in 
[move_group-3] #13   Object "/usr/lib/x86_64-linux-gnu/libc.so.6", at 0x7f31c6b1eb42, in 
[move_group-3] #12   Object "/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.30", at 0x7f31c6db02b2, in 
[move_group-3] #11   Object "/home/faheem/ws_moveit/install/moveit_ros_move_group/lib/libmoveit_move_group_default_capabilities.so.2.7.4", at 0x7f31af732d40, in move_group::MoveGroupMoveAction::executeMoveCallback(std::shared_ptr<rclcpp_action::ServerGoalHandle<moveit_msgs::action::MoveGroup> > const&)
[move_group-3] #10   Object "/home/faheem/ws_moveit/install/moveit_ros_move_group/lib/libmoveit_move_group_default_capabilities.so.2.7.4", at 0x7f31af7320e1, in move_group::MoveGroupMoveAction::executeMoveCallbackPlanAndExecute(std::shared_ptr<rclcpp_action::ServerGoalHandle<moveit_msgs::action::MoveGroup> > const&, std::shared_ptr<moveit_msgs::action::MoveGroup_Result_<std::allocator<void> > >&)
[move_group-3] #9    Object "/home/faheem/ws_moveit/install/moveit_ros_move_group/lib/libmoveit_move_group_default_capabilities.so.2.7.4", at 0x7f31af7380ac, in plan_execution::ExecutableMotionPlan::~ExecutableMotionPlan()
[move_group-3] #8    Object "/home/faheem/ws_moveit/install/moveit_ros_move_group/lib/moveit_ros_move_group/move_group", at 0x56281dd599d1, in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release()
[move_group-3] #7    Object "/home/faheem/ws_moveit/install/moveit_ros_planning/lib/libmoveit_plan_execution.so.2.7.4", at 0x7f31c6a0aac0, in std::_Sp_counted_ptr_inplace<robot_trajectory::RobotTrajectory, std::allocator<robot_trajectory::RobotTrajectory>, (__gnu_cxx::_Lock_policy)2>::_M_dispose()
[move_group-3] #6    Object "/usr/lib/x86_64-linux-gnu/libc.so.6", at 0x7f31c6b2f4d2, in free
[move_group-3] #5    Object "/usr/lib/x86_64-linux-gnu/libc.so.6", at 0x7f31c6b2cac3, in 
[move_group-3] #4    Object "/usr/lib/x86_64-linux-gnu/libc.so.6", at 0x7f31c6b2ad7b, in 
[move_group-3] #3    Object "/usr/lib/x86_64-linux-gnu/libc.so.6", at 0x7f31c6b136f5, in 
[move_group-3] #2    Object "/usr/lib/x86_64-linux-gnu/libc.so.6", at 0x7f31c6ab27f2, in abort
[move_group-3] #1    Object "/usr/lib/x86_64-linux-gnu/libc.so.6", at 0x7f31c6acc475, in raise
[move_group-3] #0    Object "/usr/lib/x86_64-linux-gnu/libc.so.6", at 0x7f31c6b20a7c, in pthread_kill
[move_group-3] Aborted (Signal sent by tkill() 3376 1000)
[ERROR] [move_group-3]: process has died [pid 3376, exit code -6, cmd '/home/faheem/ws_moveit/install/moveit_ros_move_group/lib/moveit_ros_move_group/move_group --ros-args --params-file /tmp/launch_params_rhqyce42 --params-file /tmp/launch_params_su1nw8xw'].

**Comment by kappa95** [comment]
Probably is the setting up of the ROS2 controller as written here:
```bash
[ros2_control_node-5] [ERROR] [1688366470.726299793] [right_gripper_controller]: Joint name cannot be empty
[ros2_control_node-5] [WARN] [1688366470.726340793] []: Error occurred while doing error handling.
[ros2_control_node-5] [ERROR] [1688366470.726370193] [controller_manager]: After configuring, controller 'right_gripper_controller' is in state 'unconfigured' , expected inactive.
[spawner-9] [ERROR] [1688366470.743276993] [spawner_right_gripper_controller]: Failed to configure controller
[spawner-8] [INFO] [1688366470.807704193] [spawner_left_gripper_controller]: Loaded left_gripper_controller
[ros2_control_node-5] [INFO] [1688366470.814737793] [controller_manager]: Configuring controller 'left_gripper_controller'
[ros2_control_node-5] [INFO] [1688366470.814871693] [left_gripper_controller]: Action status changes will be monitored at 20Hz.
[ros2_control_node-5] [ERROR] [1688366470.814907793] [left_gripper_controller]: Joint name cannot be empty
[ros2_control_node-5] [WARN] [1688366470.814932193] []: Error occurred while doing error handling.
[ros2_control_node-5] [ERROR] [1688366470.814947793] [controller_manager]: After configuring, controller 'left_gripper_controller' is in state 'unconfigured' , expected inactive.
[spawner-8] [ERROR] [1688366470.822987693] [spawner_left_gripper_controller]: Failed to configure controller
[INFO] [spawner-6]: process has finished cleanly [pid 7943]
[INFO] [spawner-7]: process has finished cleanly [pid 7945]
[INFO] [spawner-10]: process has finished cleanly [pid 7979]
[ERROR] [spawner-9]: process has died [pid 7964, exit code 1, cmd '/opt/ros/humble/lib/controller_manager/spawner right_gripper_controller --ros-args'].
[ERROR] [spawner-8]: process has died [pid 7957, exit code 1, cmd '/opt/ros/humble/lib/controller_manager/spawner left_gripper_controller --ros-args'].
```

In Setup Assistant check the ROS2 controller section: add the FollowJointTrajectory controller for right and left group. The same name for the moveit controller. You could check the settings in the files: `ros2_controllers.yaml` and `moveit_controllers.yaml`

**Comment by faheem-khaskheli** [comment]
i followed moveit setup assistant, in this for gripper there is gripper command for moveit controller, and for ros controller there is gripper action controller, i selected those.
so you are saying i have to select FollowJointTrajectory. in ros2 controller only, while moveit controller will have gripper command.

**Comment by kappa95** [comment]
> i followed moveit setup assistant, in this for gripper there is gripper command for moveit controller, and for ros controller there is gripper action controller, i selected those.
> so you are saying i have to select FollowJointTrajectory. in ros2 controller. 

If you give a look on how the panda moveit config is made, you see that on the ros2 controller yaml file you have this type of controller:

      type: position_controllers/GripperActionController

Check the moveit gripper controller.yaml of the panda to have a reference of what it could be used.

**Comment by faheem-khaskheli** [comment]
my files

# ros2_controllers.yaml
```
# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    left_gripper_controller:
      type: position_controllers/GripperActionController


    right_gripper_controller:
      type: position_controllers/GripperActionController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

left_arm_controller:
  ros__parameters:
    joints:
      - arm_left_1_joint
      - arm_left_2_joint
      - arm_left_3_joint
      - arm_left_4_joint
      - arm_left_5_joint
      - arm_left_6_joint
      - arm_left_7_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
right_arm_controller:
  ros__parameters:
    joints:
      - arm_right_1_joint
      - arm_right_2_joint
      - arm_right_3_joint
      - arm_right_4_joint
      - arm_right_5_joint
      - arm_right_6_joint
      - arm_right_7_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
left_gripper_controller:
  ros__parameters:
    joints:
      - left_hand_gripper_left_finger_joint
      - left_hand_gripper_right_finger_joint
right_gripper_controller:
  ros__parameters:
    joints:
      - right_hand_gripper_left_finger_joint
      - right_hand_gripper_right_finger_joint
```

# moveit_controllers.yaml
```
# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - left_arm_controller
    - right_arm_controller
    - left_gripper_controller
    - right_gripper_controller

  left_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - arm_left_1_joint
      - arm_left_2_joint
      - arm_left_3_joint
      - arm_left_4_joint
      - arm_left_5_joint
      - arm_left_6_joint
      - arm_left_7_joint
  right_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - arm_right_1_joint
      - arm_right_2_joint
      - arm_right_3_joint
      - arm_right_4_joint
      - arm_right_5_joint
      - arm_right_6_joint
      - arm_right_7_joint
  left_gripper_controller:
    type: GripperCommand
    joints:
      - left_hand_gripper_left_finger_joint
      - left_hand_gripper_right_finger_joint
    action_ns: gripper_cmd
    default: true
  right_gripper_controller:
    type: GripperCommand
    joints:
      - right_hand_gripper_left_finger_joint
      - right_hand_gripper_right_finger_joint
    action_ns: gripper_cmd
    default: true
```
